### ISSUE TITLE
Configuration is broken when no local clamav binary available

### ISSUE THREAD

**Issue by vasyas** [kylefarris/clamscan#30]
Initializing

```
    clamScan = await new NodeClam().init({
        debug_mode: true,
        clamdscan: {
            host: config.clamav.host,
            port: config.clamav.port,
            socket: null,
        },
    })
```

Further access fails with
```
(node:2119) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at local_fallback (/Users/vasyas/projects/elpaso/server/node_modules/clamscan/index.js:625:61)
    at Promise (/Users/vasyas/projects/elpaso/server/node_modules/clamscan/index.js:674:24)
    at Promise._execute (/Users/vasyas/projects/elpaso/server/node_modules/bluebird/js/release/debuggability.js:313:9)
```

**Comment by asabhaney** [comment]
I am encountering this issue as well
