### ISSUE TITLE
There is EOF error on scanning an infected file by using passthrough

### ISSUE THREAD

**Issue by czzyoyo** [kylefarris/clamscan#42]
Scanning an infected file by using 'is_infected' worked well. But there is uncaught error when using passthrough. 
W20200120-14:47:30.649(8)? (STDERR) events.js:183
W20200120-14:47:30.650(8)? (STDERR)       throw er; // Unhandled 'error' event
W20200120-14:47:30.650(8)? (STDERR)       ^
W20200120-14:47:30.650(8)? (STDERR)
W20200120-14:47:30.650(8)? (STDERR) Error: stream.push() after EOF
W20200120-14:47:30.650(8)? (STDERR)     at readableAddChunk (_stream_readable.js:240:30)
W20200120-14:47:30.650(8)? (STDERR)     at NodeClamTransform.Readable.push (_stream_readable.js:208:10)
W20200120-14:47:30.651(8)? (STDERR)     at NodeClamTransform.Transform.push (_stream_transform.js:147:32)
W20200120-14:47:30.651(8)? (STDERR)     at NodeClamTransform._flush (/npm/node_modules/clamscan/NodeClamTransform.js:38:14)
W20200120-14:47:30.651(8)? (STDERR)     at NodeClamTransform.prefinish (_stream_transform.js:137:10)
W20200120-14:47:30.651(8)? (STDERR)     at emitNone (events.js:106:13)
W20200120-14:47:30.651(8)? (STDERR)     at NodeClamTransform.emit (events.js:208:7)
W20200120-14:47:30.651(8)? (STDERR)     at prefinish (_stream_writable.js:602:14)
W20200120-14:47:30.651(8)? (STDERR)     at finishMaybe (_stream_writable.js:610:5)
W20200120-14:47:30.651(8)? (STDERR)     at endWritable (_stream_writable.js:621:3)
W20200120-14:47:30.651(8)? (STDERR)     at NodeClamTransform.Writable.end (_stream_writable.js:572:5)
W20200120-14:47:30.652(8)? (STDERR)     at NodeClamTransform.Duplex._destroy (_stream_duplex.js:118:8)
W20200120-14:47:30.652(8)? (STDERR)     at NodeClamTransform.Transform._destroy (_stream_transform.js:196:29)
W20200120-14:47:30.652(8)? (STDERR)     at NodeClamTransform.destroy (internal/streams/destroy.js:32:8)
W20200120-14:47:30.652(8)? (STDERR)     at handle_error (/npm/node_modules/clamscan/index.js:927:44)

**Comment by czzyoyo** [comment]
Sorry, There is the pull request, https://github.com/kylefarris/clamscan/pull/41, so close
